// Auto-generated Wails bindings stub — regenerated by `wails generate module`

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const go = (window as any)?.go?.main?.App ?? {}

export async function GetTracks() {
  return go.GetTracks?.() ?? []
}
export async function GetState(): Promise<number> {
  return go.GetState?.() ?? 0
}
export async function IsMetronomeActive(): Promise<boolean> {
  return go.IsMetronomeActive?.() ?? false
}
export async function SelectTrack(id: number): Promise<void> {
  return go.SelectTrack?.(id)
}
export async function PrevTrack(): Promise<void> {
  return go.PrevTrack?.()
}
export async function NextTrack(): Promise<void> {
  return go.NextTrack?.()
}
export async function Record(): Promise<void> {
  return go.Record?.()
}
export async function Overdub(): Promise<void> {
  return go.Overdub?.()
}
export async function Play(): Promise<void> {
  return go.Play?.()
}
export async function Stop(): Promise<void> {
  return go.Stop?.()
}
export async function Undo(): Promise<void> {
  return go.Undo?.()
}
export async function MuteActiveTrack(): Promise<void> {
  return go.MuteActiveTrack?.()
}
export async function ClearActiveTrack(): Promise<void> {
  return go.ClearActiveTrack?.()
}
export async function ToggleMetronome(): Promise<void> {
  return go.ToggleMetronome?.()
}

export interface UpdateInfo {
  hasUpdate: boolean
  latestVersion: string
  currentVersion: string
  downloadURL: string
  releaseNotes: string
}

export async function CheckForUpdates(): Promise<UpdateInfo> {
  return go.CheckForUpdates?.() ?? { hasUpdate: false, latestVersion: '', currentVersion: '', downloadURL: '', releaseNotes: '' }
}
export async function DownloadAndInstallUpdate(downloadURL: string): Promise<void> {
  return go.DownloadAndInstallUpdate?.(downloadURL)
}
